# Generated by Django 4.1.2 on 2022-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_room_dir_alter_message_body_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
