# Generated by Django 4.1.2 on 2022-11-15 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_data_descrtiption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
