# Generated by Django 4.1.2 on 2022-11-15 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_rename_descrtiption_data_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
