# Generated by Django 4.1.2 on 2022-11-22 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_data_room_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='Topic',
            new_name='RiverBasin',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='room',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='topic',
            new_name='river_basin',
        ),
        migrations.RemoveField(
            model_name='data',
            name='room_files',
        ),
        migrations.AddField(
            model_name='data',
            name='location_files',
            field=models.ManyToManyField(related_name='location_files', to='app.location'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
