# Generated by Django 4.1.2 on 2022-11-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_room_location_rename_topic_riverbasin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='river_basin',
            new_name='basin',
        ),
    ]
